# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)
footprint_model: "circular" # types: "point", "circular", "two_circles", "line", "polygon"
radius: 0.40

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.3

resolution: 0.05 #to put 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: odom
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: 
        data_type: LaserScan
        topic: /scan
        marking: true
        clearing: true
        min_obstacle_height: 0.0
        max_obstacle_height: 0.35  #TO CHANGE

inflation:
    cost_scaling_factor: 10.00  #default 5 #exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius: 0.20 # max. distance from an obstacle at which costs are incurred for planning paths.





