global_frame: odom
robot_base_frame: base_link
rolling_window: true
static_map: true #add during the trials of 28/01/2019
update_frequency: 5.0
publish_frequency: 0.0
track_unknown_space: true

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}


