global_frame: odom
robot_base_frame: base_link
update_frequency: 5.0 #5.0
publish_frequency: 5.0 #2.0
static_map: false
rolling_window: true
width: 3
height: 3
resolution: 0.05 #to put 0.05
origin_x: 0.0
origin_y: 0.0


plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}


